config/routes.rb
Rails.application.routes.draw do
  resources :orders do  
    resources:orderitems
  end
  get 'static_pages/homecategory'

  resources :items
  resources :categories
  devise_for :users do  
    resources:orders
  end
  get '/checkout' => 'cart#createOrder'
  get '/paid' => 'static_pages#paid'
  get 'cart/index'
  root :controller => 'static_pages', :action => 'home'
  get 'static_pages/home'
  
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'

  get '/login' => 'user#user_login'
  get '/logout' => 'user#logout'

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  
  post '/search' => 'items#search'
  get '/homecategory'=> 'static_pages#homecategory' 
  get '/homecategory/:title', to: 'static_pages#homecategory'
  get '/pcbuilder/:config', to: 'static_pages#pcbuilder'
  get '/cart/build/:config', to: 'cart#build'
  root 'site#home'

end

app/views/layouts/_categories.html.erb
           <% @categories.each do |category| %>
            <p><a href="/homecategory/<%= category.name %>"><%= category.name %></a></p>
          <% end %>      

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; PC Parts Online &trade; 2017
    </small>
</footer>

app/views/layouts/_header.html.erb
   
        <div><h2 id="logo">PC Parts Online</h2></div>
       
       <div><%= link_to image_tag("cart.png", :style => "height:80px; float:right; padding: 5px" ),   cart_path %></div>
        <div id="topmenu">
            <p>
              <ul class="headermenu">
                <li class="liheadermenu"><%= link_to "Home", root_path %></li>
                <li class="liheadermenu"><%= link_to "Products", items_path %></li>
                <li class="liheadermenu"><%= link_to "Help", help_path %></li>
                <li class="liheadermenu"><%= link_to "About", about_path %></li>
              </ul>
          </p>
        </div>

        <div class="search">
            <%= form_tag("/search" , :method => "post") do %>
            <%= label_tag("Search for:") %>
            <%= text_field_tag(:q) %>
            <%= submit_tag("Search") %>
            <% end %>
        </div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | PcPartsOnline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 

    <div id="main">
       <div class="header">
          <%= render 'layouts/header' %>
      </div>
      <div id="leftmenu">
        <% if current_user.try(:admin?) %>
          <p><%= link_to 'Categories', categories_path %></p>
          <p><%= link_to 'New Category', new_category_path %></p>
          <p><%= link_to 'Items', items_path %></p>
          <p><%= link_to 'New Item' , new_item_path %></p>
          <p><%= link_to "View Orders", orders_path  %></p>

        <% else %>
            <%=render 'layouts/categories'%>
            <p><a href='/pcbuilder/{"CPU":{"id":"","socket_type":"", "memory_type":""},"Motherboard":{"id":"","socket_type":"", "memory_type":""},"Memory":{"id":"","socket_type":"", "memory_type":""},"GPU":{"id":"","socket_type":"", "memory_type":""},"DVD-Bluray":{"id":"","socket_type":"", "memory_type":""},"Chassis":{"id":"","socket_type":"", "memory_type":""},"PSU":{"id":"","socket_type":"", "memory_type":""},"Screen":{"id":"","socket_type":"", "memory_type":""},"HDD":{"id":"","socket_type":"", "memory_type":""},"SSD":{"id":"","socket_type":"", "memory_type":""}}'>PC Builder</a></p>
        <% end %>
      </div>
      <div id='content'>
        <p class='notice'><%= flash[:notice]%></p>
        <%= yield %>       
      </div>
      <div id='rightmenu'>
        <div class="loginbox">
          <% if user_signed_in? %>
                 <div>Signed in as... <%= current_user.email %> <br/> (<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>) <%= link_to 'Edit Profile', edit_user_registration_path %></div>
          <% else %>
                 <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
          <% end %>
        </div>
      </div>

  <%= render 'layouts/footer' %>

    </div>

</body>
</html>